// ============================================
// PODIATRY ANATOMY TERMS DATABASE (100+ terms)
// ============================================
const TERMS = [
    // BONES (30 terms)
    { word: "TALUS", category: "Bones", hint: "A tarsal bone that transmits body weight from the tibia to the foot, articulating with the tibia, fibula, and calcaneus." },
    { word: "CALCANEUS", category: "Bones", hint: "The largest tarsal bone, forming the heel. It articulates with the talus and cuboid." },
    { word: "CUBOID", category: "Bones", hint: "A tarsal bone on the lateral column of the foot, articulating proximally with the calcaneus and distally with the fourth and fifth metatarsals." },
    { word: "NAVICULAR", category: "Bones", hint: "A tarsal bone on the medial side of the foot, situated between the talus and the three cuneiform bones." },
    { word: "CUNEIFORM", category: "Bones", hint: "Three wedge-shaped bones (medial, intermediate, lateral) in the midfoot region." },
    { word: "METATARSAL", category: "Bones", hint: "One of five long bones in the forefoot, articulating proximally with the tarsus and distally with the proximal phalanges." },
    { word: "PHALANX", category: "Bones", hint: "One of the small bones forming the digits; the hallux has two while each lesser toe has three." },
    { word: "SESAMOID", category: "Bones", hint: "Small ossicles found within tendons that reduce friction and alter the direction of muscle pull, commonly found beneath the first metatarsal head." },
    { word: "HALLUX", category: "Bones", hint: "The most medial digit of the foot, consisting of two phalanges and lacking a middle phalanx." },
    { word: "FIBULA", category: "Bones", hint: "A relatively thin long bone of the lower leg that is not primarily weight-bearing but forms part of the ankle joint laterally." },
    { word: "TIBIA", category: "Bones", hint: "The primary weight-bearing bone of the lower leg, broader at its proximal end and forming the shin." },
    { word: "MALLEOLUS", category: "Bones", hint: "The bony prominence on either side of the ankle; medial (from the tibia) or lateral (from the fibula)." },
    { word: "SUSTENTACULUM", category: "Bones", hint: "The shelf-like projection on the medial aspect of the calcaneus supporting the talus." },
    { word: "TROCHLEA", category: "Bones", hint: "The superior articular surface of the talus that articulates with the tibia." },
    { word: "TUBEROSITY", category: "Bones", hint: "A bony prominence serving as an attachment site for muscles or ligaments." },
    { word: "STYLOID", category: "Bones", hint: "A pointed bony projection, such as found at the base of the 5th metatarsal." },
    { word: "TUBERCLE", category: "Bones", hint: "A small rounded projection on a bone for muscle or ligament attachment." },
    { word: "CONDYLE", category: "Bones", hint: "A rounded articular surface at the end of a bone." },
    { word: "EPIPHYSIS", category: "Bones", hint: "The end portion of a long bone, initially separated from the shaft by cartilage during growth." },
    { word: "DIAPHYSIS", category: "Bones", hint: "The shaft or central portion of a long bone." },
    { word: "PERIOSTEUM", category: "Bones", hint: "The fibrous membrane covering the outer surface of bones." },
    { word: "CORTEX", category: "Bones", hint: "The dense outer layer of compact bone tissue." },
    { word: "TRABECULAE", category: "Bones", hint: "The lattice-like structure of spongy (cancellous) bone." },
    { word: "OSSICLE", category: "Bones", hint: "A small accessory bone, sometimes found in the foot." },
    { word: "APOPHYSIS", category: "Bones", hint: "A bony outgrowth that develops from a separate ossification centre." },

    // MUSCLES (15 terms)
    { word: "GASTROCNEMIUS", category: "Muscles", hint: "The large superficial calf muscle with two heads, a powerful plantarflexor of the foot." },
    { word: "SOLEUS", category: "Muscles", hint: "The deep calf muscle beneath the gastrocnemius, a key postural muscle for plantarflexion." },
    { word: "TIBIALIS", category: "Muscles", hint: "Muscles named for their tibial attachment; the anterior inverts and dorsiflexes, the posterior inverts and plantarflexes." },
    { word: "PERONEUS", category: "Muscles", hint: "Also known as fibularis muscles; these evert the foot and assist with plantarflexion." },
    { word: "FIBULARIS", category: "Muscles", hint: "Modern anatomical term for the peroneal muscles; includes longus, brevis, and tertius." },
    { word: "FLEXOR", category: "Muscles", hint: "Muscles that curl the toes; includes hallucis longus/brevis and digitorum longus/brevis." },
    { word: "EXTENSOR", category: "Muscles", hint: "Muscles that straighten the toes; includes hallucis longus and digitorum longus/brevis." },
    { word: "ABDUCTOR", category: "Muscles", hint: "Muscles that move toes away from the midline; includes hallucis and digiti minimi." },
    { word: "ADDUCTOR", category: "Muscles", hint: "A muscle that moves the great toe toward the midline of the foot." },
    { word: "LUMBRICAL", category: "Muscles", hint: "Four small intrinsic muscles that flex the metatarsophalangeal joints and extend the interphalangeal joints." },
    { word: "INTEROSSEI", category: "Muscles", hint: "Small muscles between metatarsals; the plantar group adducts toes, the dorsal group abducts them." },
    { word: "QUADRATUS", category: "Muscles", hint: "A quadrangular muscle of the sole that assists the flexor digitorum longus in toe flexion." },
    { word: "PLANTARIS", category: "Muscles", hint: "A small, thin muscle in the posterior leg with a very long tendon that may be absent in some individuals." },
    { word: "POPLITEUS", category: "Muscles", hint: "A muscle at the back of the knee that medially rotates the tibia to unlock the extended knee." },
    { word: "TRICEPS", category: "Muscles", hint: "A group of three muscles — the combined gastrocnemius and soleus, also known as triceps surae." },

    // TENDONS, LIGAMENTS & CONNECTIVE TISSUES (16 terms)
    { word: "ACHILLES", category: "Tendons & Ligaments", hint: "The common tendon of the gastrocnemius and soleus muscles, inserting on the posterior calcaneus." },
    { word: "PLANTAR", category: "Tendons & Ligaments", hint: "Relating to the sole of the foot; the plantar fascia is a key supporting structure of the arch." },
    { word: "FASCIA", category: "Tendons & Ligaments", hint: "A sheet of connective tissue; the plantar fascia supports the longitudinal arch of the foot." },
    { word: "DELTOID", category: "Tendons & Ligaments", hint: "A strong triangular ligament on the medial side of the ankle connecting the tibia to the tarsal bones." },
    { word: "TALOFIBULAR", category: "Tendons & Ligaments", hint: "Ligaments connecting the talus to the fibula; includes anterior and posterior portions." },
    { word: "CALCANEOFIBULAR", category: "Tendons & Ligaments", hint: "A lateral ankle ligament connecting the calcaneus to the fibula." },
    { word: "SPRING", category: "Tendons & Ligaments", hint: "The plantar calcaneonavicular ligament that supports the head of the talus and maintains the arch." },
    { word: "BIFURCATE", category: "Tendons & Ligaments", hint: "A Y-shaped ligament on the dorsum of the foot, connecting the calcaneus to both the navicular and cuboid." },
    { word: "RETINACULUM", category: "Tendons & Ligaments", hint: "Band-like fibrous structures that hold tendons in place as they cross the ankle joint." },
    { word: "SYNDESMOSIS", category: "Tendons & Ligaments", hint: "The fibrous joint between the distal tibia and fibula, stabilized by multiple ligaments." },
    { word: "COLLATERAL", category: "Tendons & Ligaments", hint: "Ligaments on the sides of synovial joints that provide lateral stability during movement." },
    { word: "CAPSULE", category: "Tendons & Ligaments", hint: "The fibrous tissue enclosing a synovial joint, lined internally by synovial membrane." },
    { word: "SYNOVIUM", category: "Tendons & Ligaments", hint: "The membrane lining joint capsules that produces fluid to lubricate and nourish the joint." },
    { word: "BURSA", category: "Tendons & Ligaments", hint: "A fluid-filled sac that reduces friction between tissues such as tendons, bones, and skin." },
    { word: "SHEATH", category: "Tendons & Ligaments", hint: "A tubular synovial covering around tendons that allows smooth gliding against surrounding structures." },
    { word: "APONEUROSIS", category: "Tendons & Ligaments", hint: "A flat, sheet-like tendon; the plantar aponeurosis is a key supporting structure of the foot arch." },

    // NERVES & BLOOD VESSELS (10 terms)
    { word: "TIBIAL", category: "Nerves & Vessels", hint: "A major nerve and accompanying vessels that pass behind the medial malleolus into the foot." },
    { word: "PERONEAL", category: "Nerves & Vessels", hint: "A nerve that wraps around the neck of the fibula before dividing into superficial and deep branches." },
    { word: "SURAL", category: "Nerves & Vessels", hint: "A sensory nerve supplying the skin over the lateral aspect of the foot and little toe." },
    { word: "SAPHENOUS", category: "Nerves & Vessels", hint: "The longest vein in the body, running along the medial side of the lower limb and passing anterior to the medial malleolus." },
    { word: "DORSALIS", category: "Nerves & Vessels", hint: "The main artery supplying the top of the foot, a continuation of the anterior tibial artery." },
    { word: "PLANTAR", category: "Nerves & Vessels", hint: "The paired nerves and blood vessels that supply the intrinsic muscles and skin of the sole of the foot." },
    { word: "DIGITAL", category: "Nerves & Vessels", hint: "Nerves and arteries that supply the individual toes, branching from common trunks in the forefoot." },
    { word: "TARSAL", category: "Nerves & Vessels", hint: "A fibro-osseous tunnel behind the medial malleolus containing neurovascular structures passing into the foot." },
    { word: "METATARSAL", category: "Nerves & Vessels", hint: "Dorsal and plantar arteries that supply the forefoot, running between the long bones." },
    { word: "PERFORATING", category: "Nerves & Vessels", hint: "Arteries that connect the dorsal and plantar circulations by passing through the intermetatarsal spaces." },

    // REGIONS & SURFACES (15 terms)
    { word: "DORSAL", category: "Regions", hint: "The top surface of the foot, also known as the dorsum." },
    { word: "PLANTAR", category: "Regions", hint: "The sole or bottom surface of the foot that contacts the ground during standing." },
    { word: "MEDIAL", category: "Regions", hint: "The inner side of the foot, toward the midline of the body." },
    { word: "LATERAL", category: "Regions", hint: "The outer side of the foot, away from the midline of the body." },
    { word: "PROXIMAL", category: "Regions", hint: "Closer to the centre of the body; the heel is proximal relative to the toes." },
    { word: "DISTAL", category: "Regions", hint: "Further from the centre of the body; the toes are distal relative to the heel." },
    { word: "ANTERIOR", category: "Regions", hint: "Toward the front of the body; the toes are anterior to the ankle." },
    { word: "POSTERIOR", category: "Regions", hint: "Toward the back of the body; the heel is posterior to the forefoot." },
    { word: "FOREFOOT", category: "Regions", hint: "The front part of the foot containing the metatarsals and phalanges." },
    { word: "MIDFOOT", category: "Regions", hint: "The middle part of the foot containing the tarsal bones (navicular, cuboid, cuneiforms)." },
    { word: "REARFOOT", category: "Regions", hint: "The back part of the foot consisting of the talus and calcaneus." },
    { word: "HINDFOOT", category: "Regions", hint: "Another term for the rearfoot region containing the talus and calcaneus." },
    { word: "ARCH", category: "Regions", hint: "A curved structural arrangement of bones and soft tissues that distributes weight during standing and gait; has medial, lateral, and transverse components." },
    { word: "SULCUS", category: "Regions", hint: "A groove or furrow; at the toes, this is where the nail plate meets the surrounding skin." },
    { word: "INTERDIGITAL", category: "Regions", hint: "The spaces between adjacent toes." }
];
